### ISSUE TITLE
issue with threading

### ISSUE THREAD

**Issue by pchocholac** [seprich/py-bson-rpc#2]
Hi Jussi,
I have found issue in the threading (appears randomly based on timing) in dispatcher.
Is there way to contribute patch to fix it? can I send it to you?

Thank you
Petr

PS: great framework - thank you

**Comment by seprich** [comment]
Sure, fork the repository, fix to your own copy and make a pull request, so I can review and merge.

**Comment by seprich** [comment]
Did some stress testing with server answering to a client with 800 threads, also tested with gevent Greenlets. Could not find any problem, so I am going to close this issue for now. Feel free to reopen when you have details or to leave a message to https://gitter.im/seprich/py-bson-rpc
