### ISSUE TITLE
No easy way to override the codec for a connection.

### ISSUE THREAD

**Issue by fake-name** [seprich/py-bson-rpc#4]
Hi there!

I'm using `py-bson-rpc` with the [plain `bson` library](https://github.com/py-bson/bson), which, confusingly enough, collides with mongo's (inappopriately) placed `bson` library.

As such, I need to be able to override the codec used for a connection, and there seems to be no really elegant way to do so.

Right now, I have a subclass of `BSONCodec` that simply overloads `__init__` to define different `_dumps` and `_loads`, but to install it, I have to also subclass `RpcBase`, and overload it's `__init__` with a different codec value.

Is there any reason the codec class couldn't be one of the optional parameters to `BSONRpc`?

(My patches here: https://github.com/fake-name/ReadableWebProxy/blob/master/common/fixed_bsonrpc.py#L76 )

**Comment by seprich** [comment]
Hi, thanks for the interest in this lib.. Certainly should be trivial enough to parameterize the bson library selection / injection through options, I will look onto this soon.

**Comment by fake-name** [comment]
Certainly, no hurry. I just thought it'd be a nice tweak.

**Comment by seprich** [comment]
Implemented in version 0.2.0

**Comment by fake-name** [comment]
Awesome!
